// <auto-generated />
using System;
using Alarm.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alarm.Infrastructure.Migrations
{
    [DbContext(typeof(AlarmLocalDbContext))]
    partial class AlarmLocalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Alarm.Core.Models.AlarmMode", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("AlarmModes");
                });

            modelBuilder.Entity("Alarm.Core.Models.AlarmUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("DaysOfWeek")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModeName");

                    b.ToTable("Alarm");
                });

            modelBuilder.Entity("Alarm.Core.Models.AlarmUnit", b =>
                {
                    b.HasOne("Alarm.Core.Models.AlarmMode", "Mode")
                        .WithMany()
                        .HasForeignKey("ModeName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mode");
                });
#pragma warning restore 612, 618
        }
    }
}
